# Generated by Django 4.0.4 on 2022-06-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name', 'measurement_unit'), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'ordering': ('metric', 'name'), 'verbose_name': 'Measurement unit', 'verbose_name_plural': 'Measurement units'},
        ),
    ]
